#! /bin/zsh


echo "Setting up ../config/sync as the configuration directory in settings.ddev.php"
while [ ! -f web/sites/default/settings.ddev.php ]; do
  echo "Waiting for settings.ddev.php to be created..."
  sleep 0.1
done
sed -i '' "s|sites/default/files/sync|../config/sync|g" web/sites/default/settings.ddev.php

